site_name: BrazilFiscalReport
site_url: https://engenere.github.io/BrazilFiscalReport/
repo_url: https://github.com/Engenere/BrazilFiscalReport
repo_name: Engenere/BrazilFiscalReport

theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - header.autohide
    - search.highlight
    - search.share
    - content.code.copy
  logo: 'favicon.ico'
  favicon: 'favicon.ico'

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt
          name: Português
          build: true
          nav_translations:
            Home: Início
            Getting Started: Começando
            Documents: Documentos
            CLI: CLI
            Changelog: Changelog
            Contributing: Contribuindo
            About: Sobre

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Documents:
      - DANFE: danfe.md
      - DACTE: dacte.md
      - DAMDFE: damdfe.md
      - DACCe: dacce.md
  - CLI: cli.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - About: about.md
